openapi: 3.0.1
info:
  title: RideServiceAPI
  version: v1
servers:
  - url: /
security:
  - default: []
paths:
  '/ridesPerUser/{userId}':
    get:
      parameters:
        - name: userId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: string
        - name: startDate
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: integer
        - name: endDate
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: integer
      responses:
        '200':
          description: ok
      security:
        - default: []
  '/rideDetails/{rideId}':
    get:
      parameters:
        - name: rideId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: string
        - name: expand
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: boolean
      responses:
        '200':
          description: ok
      security:
        - default: []
  /create:
    post:
      parameters: []
      responses:
        '200':
          description: ok
      security:
        - default: []
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://test.com'
          scopes: {}
